# Generated by Django 3.2.12 on 2022-03-16 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter pet's name.", max_length=20)),
                ('color', models.CharField(choices=[('8-Bit', '8-Bit'), ('Agueena', 'Agueena'), ('Alien', 'Alien'), ('Baby', 'Baby')], default='8-Bit', max_length=20)),
                ('species', models.CharField(choices=[('Acara', 'Acara'), ('Aisha', 'Aisha'), ('Blumaroo', 'Blumaroo'), ('Bori', 'Bori')], default='Acara', max_length=20)),
                ('converted', models.BooleanField(default=True)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5000)], verbose_name='Level')),
                ('health', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100000)], verbose_name='Hit Points')),
                ('strength', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100000)], verbose_name='Strength')),
                ('defence', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100000)], verbose_name='Defence')),
                ('movement', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100000)], verbose_name='Movement')),
                ('custom', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='None', help_text='Add in any notes about the pet here.', max_length=500, verbose_name='Notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
