# Generated by Django 3.2.12 on 2022-03-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
